import React from 'react';
import { useParams } from 'react-router-dom';

// Import all program components
import AIMLAgricultureProgram from './programs/AIMLAgricultureProgram';
import GeneralAgricultureProgram from './programs/GeneralAgricultureProgram';
import RoboticsProgram from './programs/RoboticsProgram';
import CybersecurityProgram from './programs/CybersecurityProgram';
import DataScienceProgram from './programs/DataScienceProgram';
import IoTProgram from './programs/IoTProgram';
import GameDevelopmentProgram from './programs/GameDevelopmentProgram';
import ElectricVehicleProgram from './programs/ElectricVehicleProgram';
import HumanComputerInteractionProgram from './programs/HumanComputerInteractionProgram';
import AIBusinessProgram from './programs/AIBusinessProgram';
import AICybersecurityProgram from './programs/AICybersecurityProgram';
import AIBlockchainProgram from './programs/AIBlockchainProgram';
import AgricultureRoboticsProgram from './programs/AgricultureRoboticsProgram';
import AgriEntrepreneurshipProgram from './programs/AgriEntrepreneurshipProgram';

import HydroponicsFarmingProgram from './programs/HydroponicsFarmingProgram';
import FermentationTechnologyProgram from './programs/FermentationTechnologyProgram';
import VaccineTechnologyProgram from './programs/VaccineTechnologyProgram';
import MedicalCodingProgram from './programs/MedicalCodingProgram';
import IPLawProgram from './programs/IPLawProgram';

// Import new program components
import AgricultureDronesProgram from './programs/AgricultureDronesProgram';
import AdvancedTechnologiesAgricultureProgram from './programs/AdvancedTechnologiesAgricultureProgram';
import GenerativeAIProgram from './programs/GenerativeAIProgram';
import AIBiologicalSciencesProgram from './programs/AIBiologicalSciencesProgram';
import AILawProgram from './programs/AILawProgram';
import AIMarketingProgram from './programs/AIMarketingProgram';
import ClinicalResearchRegulatoryAffairsProgram from './programs/ClinicalResearchRegulatoryAffairsProgram';
import DigitalForensicsProgram from './programs/DigitalForensicsProgram';
import BioentrepreneurshipProgram from './programs/BioentrepreneurshipProgram';
import AIDesigningTechnologyProgram from './programs/AIDesigningTechnologyProgram';
import AIArtsProgram from './programs/AIArtsProgram';
import ARVRXRDevelopmentProgram from './programs/ARVRXRDevelopmentProgram';
import VirtualAugmentedRealityEngineeringProgram from './programs/VirtualAugmentedRealityEngineeringProgram';
import AIManagementCertificateProgram from './programs/AIManagementCertificateProgram';
import ARVRTechnologyProgram from './programs/ARVRTechnologyProgram';
import PrecisionAgricultureProgram from './programs/PrecisionAgricultureProgram';
import AIManagementStudiesProgram from './programs/AIManagementStudiesProgram';
import DoctoralPrograms from './programs/DoctoralPrograms';
import PostdoctoralPrograms from './programs/PostdoctoralPrograms';

const ProgramRouter: React.FC = () => {
  const { programSlug } = useParams<{ programSlug: string }>();
  

  // Program mapping based on actual slugs generated by ProgramCard component
  const programComponents: { [key: string]: React.ComponentType } = {
    // Precision Agriculture Programs
    'precision-agriculture': PrecisionAgricultureProgram,
    'agriculture-drones': AgricultureDronesProgram,
    'hydroponics-farming': HydroponicsFarmingProgram,
    'advanced-technologies-agriculture': AdvancedTechnologiesAgricultureProgram,
    'agriculture-robotics': AgricultureRoboticsProgram,
    'ai-ml-agriculture': AIMLAgricultureProgram,
    'agriculture': GeneralAgricultureProgram,
    'agri-entrepreneurship': AgriEntrepreneurshipProgram,
    
    // AI & Robotics Programs
    'robotics': RoboticsProgram,
    'generative-ai': GenerativeAIProgram,
    'ai-blockchain': AIBlockchainProgram,
    'data-science': DataScienceProgram,
    'ai-biological-sciences': AIBiologicalSciencesProgram,
    'ai-cybersecurity': AICybersecurityProgram,
    'cybersecurity': CybersecurityProgram,
    
    // AI & Business Programs
    'ai-business': AIBusinessProgram,
    'ai-management-studies': AIManagementStudiesProgram,
    'ai-law': AILawProgram,
    'ip-law': IPLawProgram,
    'ai-marketing': AIMarketingProgram,
    
    // Healthcare & Life Sciences
    'clinical-research-regulatory-affairs': ClinicalResearchRegulatoryAffairsProgram,
    'medical-coding': MedicalCodingProgram,
    'digital-forensics': DigitalForensicsProgram,
    'fermentation-technology': FermentationTechnologyProgram,
    'vaccine-technology': VaccineTechnologyProgram,
    'bioentrepreneurship': BioentrepreneurshipProgram,
    
    // AI & Creative Technologies
    'ai-designing-technology': AIDesigningTechnologyProgram,
    'ai-arts': AIArtsProgram,
    
    // Emerging Technologies & Smart Systems
    'reality-architect-master-of-arvrxr-development': ARVRXRDevelopmentProgram,
    'virtual-vanguard-master-in-virtual-augmented-reality-engineering': VirtualAugmentedRealityEngineeringProgram,
    'electric-vehicle': ElectricVehicleProgram,
    'iot': IoTProgram,
    'human-computer-interaction': HumanComputerInteractionProgram,
    
    // Homepage Specific Programs
    'ai-management-certificate': AIManagementCertificateProgram,
    'ar-vr-technology': ARVRTechnologyProgram,
    
    // Doctoral & Postdoctoral Programs
    'doctoral-programs': DoctoralPrograms,
    'postdoctoral-programs': PostdoctoralPrograms,
    
    // Additional consolidated mappings
    'game-development': GameDevelopmentProgram,
    'data-analytics': DataScienceProgram
  };

  // Get the component for the requested program
  const ProgramComponent = programComponents[programSlug || ''];
  

  if (!ProgramComponent) {
    return (
      <div className="program-details-page">
        <div className="container">
          <div className="error-state">
            <h2>Program Not Found</h2>
            <p>The requested program "{programSlug}" could not be found. Please go back to the programs page and try again.</p>
            <p>Available programs: {Object.keys(programComponents).slice(0, 10).join(', ')}...</p>
          </div>
        </div>
      </div>
    );
  }

  return <ProgramComponent />;
};

export default ProgramRouter;
