import React from 'react';
import { useParams } from 'react-router-dom';

// Import all program components
import AgricultureProgram from './programs/AgricultureProgram';
import AIProgram from './programs/AIProgram';
import RoboticsProgram from './programs/RoboticsProgram';
import CybersecurityProgram from './programs/CybersecurityProgram';
import DataScienceProgram from './programs/DataScienceProgram';
import WebDevelopmentProgram from './programs/WebDevelopmentProgram';
import MobileAppDevelopmentProgram from './programs/MobileAppDevelopmentProgram';
import CloudComputingProgram from './programs/CloudComputingProgram';
import BlockchainProgram from './programs/BlockchainProgram';
import IoTProgram from './programs/IoTProgram';
import GameDevelopmentProgram from './programs/GameDevelopmentProgram';
import DigitalMarketingProgram from './programs/DigitalMarketingProgram';
import BiotechnologyProgram from './programs/BiotechnologyProgram';
// Removed duplicate ARVR program
import FintechProgram from './programs/FintechProgram';
import ElectricVehicleProgram from './programs/ElectricVehicleProgram';
import QuantumComputingProgram from './programs/QuantumComputingProgram';
import NetworkEngineeringProgram from './programs/NetworkEngineeringProgram';
import SoftwareEngineeringProgram from './programs/SoftwareEngineeringProgram';
// Removed duplicate Machine Learning program
// Removed duplicate Data Analytics program
import DatabaseManagementProgram from './programs/DatabaseManagementProgram';
import HumanComputerInteractionProgram from './programs/HumanComputerInteractionProgram';
// Removed duplicate Mixed Reality and XR Gaming programs
import AutonomousVehicleProgram from './programs/AutonomousVehicleProgram';
import HealthcareAIProgram from './programs/HealthcareAIProgram';
import AIBusinessProgram from './programs/AIBusinessProgram';
import AICybersecurityProgram from './programs/AICybersecurityProgram';
import AIBlockchainProgram from './programs/AIBlockchainProgram';
import AgricultureRoboticsProgram from './programs/AgricultureRoboticsProgram';
import AgriEntrepreneurshipProgram from './programs/AgriEntrepreneurshipProgram';

import HydroponicsFarmingProgram from './programs/HydroponicsFarmingProgram';
import FermentationTechnologyProgram from './programs/FermentationTechnologyProgram';
import VaccineTechnologyProgram from './programs/VaccineTechnologyProgram';
import MedicalCodingProgram from './programs/MedicalCodingProgram';
import IPLawProgram from './programs/IPLawProgram';
import RegulatoryAffairsProgram from './programs/RegulatoryAffairsProgram';

// Import new program components
import AgricultureDronesProgram from './programs/AgricultureDronesProgram';
import AdvancedTechnologiesAgricultureProgram from './programs/AdvancedTechnologiesAgricultureProgram';
import GenerativeAIProgram from './programs/GenerativeAIProgram';
import AIBiologicalSciencesProgram from './programs/AIBiologicalSciencesProgram';
import AILawProgram from './programs/AILawProgram';
import AIMarketingProgram from './programs/AIMarketingProgram';
import ClinicalResearchRegulatoryAffairsProgram from './programs/ClinicalResearchRegulatoryAffairsProgram';
import DigitalForensicsProgram from './programs/DigitalForensicsProgram';
import BioentrepreneurshipProgram from './programs/BioentrepreneurshipProgram';
import AIDesigningTechnologyProgram from './programs/AIDesigningTechnologyProgram';
import AIArtsProgram from './programs/AIArtsProgram';
import ARVRXRDevelopmentProgram from './programs/ARVRXRDevelopmentProgram';
import VirtualAugmentedRealityEngineeringProgram from './programs/VirtualAugmentedRealityEngineeringProgram';
import MedicalRoboticsProgram from './programs/MedicalRoboticsProgram';
import AIManagementCertificateProgram from './programs/AIManagementCertificateProgram';
import ARVRTechnologyProgram from './programs/ARVRTechnologyProgram';

const ProgramRouter: React.FC = () => {
  const { programSlug } = useParams<{ programSlug: string }>();
  
  console.log('ProgramRouter received slug:', programSlug);

  // Program mapping based on actual slugs generated by ProgramCard component
  const programComponents: { [key: string]: React.ComponentType } = {
    // Precision Agriculture Programs
    'precision-agriculture': AIProgram, // Fallback since PrecisionAgricultureProgram was deleted
    'agriculture-drones': AgricultureDronesProgram,
    'hydroponics-farming': HydroponicsFarmingProgram,
    'advanced-technologies-agriculture': AdvancedTechnologiesAgricultureProgram,
    'ai': AIProgram,
    'agriculture-robotics': AgricultureRoboticsProgram,
    'agriculture': AgricultureProgram,
    'agri-entrepreneurship': AgriEntrepreneurshipProgram,
    
    // AI & Robotics Programs
    'robotics': RoboticsProgram,
    'generative-ai': GenerativeAIProgram,
    'ai-blockchain': AIBlockchainProgram,
    'data-science': DataScienceProgram,
    'ai-biological-sciences': AIBiologicalSciencesProgram,
    'ai-cybersecurity': AICybersecurityProgram,
    'cybersecurity': CybersecurityProgram,
    
    // AI & Business Programs
    'ai-business': AIBusinessProgram,
    'ai-law': AILawProgram,
    'ip-law': IPLawProgram,
    'ai-marketing': AIMarketingProgram,
    
    // Healthcare & Life Sciences
    'clinical-research-regulatory-affairs': ClinicalResearchRegulatoryAffairsProgram,
    'medical-coding': MedicalCodingProgram,
    'digital-forensics': DigitalForensicsProgram,
    'fermentation-technology': FermentationTechnologyProgram,
    'vaccine-technology': VaccineTechnologyProgram,
    'bioentrepreneurship': BioentrepreneurshipProgram,
    
    // AI & Creative Technologies
    'ai-designing-technology': AIDesigningTechnologyProgram,
    'ai-arts': AIArtsProgram,
    
    // Emerging Technologies & Smart Systems
    'reality-architect-master-of-arvrxr-development': ARVRXRDevelopmentProgram,
    'virtual-vanguard-master-in-virtual-augmented-reality-engineering': VirtualAugmentedRealityEngineeringProgram,
    'electric-vehicle': ElectricVehicleProgram,
    'iot': IoTProgram,
    'human-computer-interaction': HumanComputerInteractionProgram,
    
    // Homepage Specific Programs
    'medical-robotics': MedicalRoboticsProgram,
    'ai-management-certificate': AIManagementCertificateProgram,
    'ar-vr-technology': ARVRTechnologyProgram,
    
    // Doctoral & Postdoctoral Programs
    'doctoral-programs': AIProgram, // Default fallback
    'postdoctoral-programs': AIProgram, // Default fallback
    
    // Additional consolidated mappings
    'web-development': WebDevelopmentProgram,
    'mobile-app-development': MobileAppDevelopmentProgram,
    'cloud-computing': CloudComputingProgram,
    'blockchain': BlockchainProgram,
    'game-development': GameDevelopmentProgram,
    'digital-marketing': DigitalMarketingProgram,
    'biotechnology': BiotechnologyProgram,
    'fintech': FintechProgram,
    'quantum-computing': QuantumComputingProgram,
    'network-engineering': NetworkEngineeringProgram,
    'software-engineering': SoftwareEngineeringProgram,
    'machine-learning': AIProgram,
    'data-analytics': DataScienceProgram,
    'database-management': DatabaseManagementProgram,
    'autonomous-vehicle': AutonomousVehicleProgram,
    'healthcare-ai': HealthcareAIProgram,
    'regulatory-affairs': RegulatoryAffairsProgram
  };

  // Get the component for the requested program
  const ProgramComponent = programComponents[programSlug || ''];
  
  console.log('Selected component:', ProgramComponent);
  console.log('Available slugs:', Object.keys(programComponents));

  if (!ProgramComponent) {
    return (
      <div className="program-details-page">
        <div className="container">
          <div className="error-state">
            <h2>Program Not Found</h2>
            <p>The requested program "{programSlug}" could not be found. Please go back to the programs page and try again.</p>
            <p>Available programs: {Object.keys(programComponents).slice(0, 10).join(', ')}...</p>
          </div>
        </div>
      </div>
    );
  }

  return <ProgramComponent />;
};

export default ProgramRouter;
