import React from 'react';
import { useParams } from 'react-router-dom';

// Import all program components
import AgricultureProgram from './programs/AgricultureProgram';
import AIProgram from './programs/AIProgram';
import RoboticsProgram from './programs/RoboticsProgram';
import CybersecurityProgram from './programs/CybersecurityProgram';
import DataScienceProgram from './programs/DataScienceProgram';
import WebDevelopmentProgram from './programs/WebDevelopmentProgram';
import MobileAppDevelopmentProgram from './programs/MobileAppDevelopmentProgram';
import CloudComputingProgram from './programs/CloudComputingProgram';
import BlockchainProgram from './programs/BlockchainProgram';
import IoTProgram from './programs/IoTProgram';
import GameDevelopmentProgram from './programs/GameDevelopmentProgram';
import DigitalMarketingProgram from './programs/DigitalMarketingProgram';
import BiotechnologyProgram from './programs/BiotechnologyProgram';
import ARVRProgram from './programs/ARVRProgram';
import FintechProgram from './programs/FintechProgram';
import ElectricVehicleProgram from './programs/ElectricVehicleProgram';
import QuantumComputingProgram from './programs/QuantumComputingProgram';
import NetworkEngineeringProgram from './programs/NetworkEngineeringProgram';
import SoftwareEngineeringProgram from './programs/SoftwareEngineeringProgram';
import MachineLearningProgram from './programs/MachineLearningProgram';
import DataAnalyticsProgram from './programs/DataAnalyticsProgram';
import DatabaseManagementProgram from './programs/DatabaseManagementProgram';
import HumanComputerInteractionProgram from './programs/HumanComputerInteractionProgram';
import MixedRealityProgram from './programs/MixedRealityProgram';
import XRGamingProgram from './programs/XRGamingProgram';
import AutonomousVehicleProgram from './programs/AutonomousVehicleProgram';
import HealthcareAIProgram from './programs/HealthcareAIProgram';
import AIBusinessProgram from './programs/AIBusinessProgram';
import AICybersecurityProgram from './programs/AICybersecurityProgram';
import AIBlockchainProgram from './programs/AIBlockchainProgram';
import AgricultureRoboticsProgram from './programs/AgricultureRoboticsProgram';
import AgriEntrepreneurshipProgram from './programs/AgriEntrepreneurshipProgram';
import PrecisionAgricultureProgram from './programs/PrecisionAgricultureProgram';
import HydroponicsFarmingProgram from './programs/HydroponicsFarmingProgram';
import FermentationTechnologyProgram from './programs/FermentationTechnologyProgram';
import VaccineTechnologyProgram from './programs/VaccineTechnologyProgram';
import MedicalCodingProgram from './programs/MedicalCodingProgram';
import IPLawProgram from './programs/IPLawProgram';
import RegulatoryAffairsProgram from './programs/RegulatoryAffairsProgram';

const ProgramRouter: React.FC = () => {
  const { programSlug } = useParams<{ programSlug: string }>();

  // Program mapping based on actual slugs generated by ProgramCard component
  const programComponents: { [key: string]: React.ComponentType } = {
    // Precision Agriculture Programs
    'master-program-in-precision-agriculture': PrecisionAgricultureProgram,
    'master-program-in-agriculture-drones': AgricultureProgram,
    'master-program-in-hydroponics-vertical-farming': HydroponicsFarmingProgram,
    'master-program-in-hydroponics--vertical-farming': HydroponicsFarmingProgram, // Handle double hyphen case
    'master-program-in-ai-ml-in-agriculture': AIProgram,
    'master-program-in-agriculture-robotics': AgricultureRoboticsProgram,
    'master-program-in-advanced-technologies-in-agriculture': AgricultureProgram,
    'master-program-in-agri-entrepreneurship': AgriEntrepreneurshipProgram,
    
    // AI & Robotics Programs
    'master-program-in-ai-robotics': RoboticsProgram,
    'master-program-in-generative-ai': AIProgram,
    'master-program-in-ai-blockchain': AIBlockchainProgram,
    'master-program-in-ai-data-analytics': DataAnalyticsProgram,
    'master-program-in-ai-biological-sciences': AIProgram,
    'master-program-in-ai-cybersecurity-systems': AICybersecurityProgram,
    'master-program-in-cybersecurity': CybersecurityProgram,
    
    // AI & Business Programs
    'master-program-in-ai-business': AIBusinessProgram,
    'master-program-in-ai-management-studies': AIBusinessProgram,
    'master-program-in-ai-law': AIProgram,
    'master-program-in-ip-law': IPLawProgram,
    'master-program-in-ai-marketing': AIProgram,
    
    // Healthcare & Life Sciences
    'master-program-in-clinical-research-regulatory-affairs': RegulatoryAffairsProgram,
    'master-program-in-medical-coding': MedicalCodingProgram,
    'master-program-in-digital-forensics': CybersecurityProgram,
    'master-program-in-industrial-fermentation-technology': FermentationTechnologyProgram,
    'master-program-in-vaccine-technology': VaccineTechnologyProgram,
    'master-program-in-bioentrepreneurship': BiotechnologyProgram,
    
    // AI & Creative Technologies
    'master-program-in-ai-designing-technology': AIProgram,
    'master-program-in-ai-arts': AIProgram,
    
    // Emerging Technologies & Smart Systems
    'reality-architect-master-of-arvrxr-development': ARVRProgram,
    'virtual-vanguard-master-in-virtual-augmented-reality-engineering': ARVRProgram,
    'game-changer-master-program-in-xr-gaming': XRGamingProgram,
    'master-program-in-ar-and-mixed-reality': MixedRealityProgram,
    'master-program-in-electric-vehicle-technology': ElectricVehicleProgram,
    'master-program-in-iot-and-embedded-systems': IoTProgram,
    'master-program-in-human-computer-interaction': HumanComputerInteractionProgram,
    
    // Doctoral & Postdoctoral Programs
    'doctoral-programs': AIProgram, // Default fallback
    'postdoctoral-programs': AIProgram, // Default fallback
    
    // Legacy mappings for backward compatibility
    'agriculture': AgricultureProgram,
    'ai': AIProgram,
    'robotics': RoboticsProgram,
    'cybersecurity': CybersecurityProgram,
    'data-science': DataScienceProgram,
    'web-development': WebDevelopmentProgram,
    'mobile-app-development': MobileAppDevelopmentProgram,
    'cloud-computing': CloudComputingProgram,
    'blockchain': BlockchainProgram,
    'iot': IoTProgram,
    'game-development': GameDevelopmentProgram,
    'digital-marketing': DigitalMarketingProgram,
    'biotechnology': BiotechnologyProgram,
    'ar-vr': ARVRProgram,
    'fintech': FintechProgram,
    'electric-vehicle': ElectricVehicleProgram,
    'quantum-computing': QuantumComputingProgram,
    'network-engineering': NetworkEngineeringProgram,
    'software-engineering': SoftwareEngineeringProgram,
    'machine-learning': MachineLearningProgram,
    'data-analytics': DataAnalyticsProgram,
    'database-management': DatabaseManagementProgram,
    'human-computer-interaction': HumanComputerInteractionProgram,
    'mixed-reality': MixedRealityProgram,
    'xr-gaming': XRGamingProgram,
    'autonomous-vehicle': AutonomousVehicleProgram,
    'healthcare-ai': HealthcareAIProgram,
    'ai-business': AIBusinessProgram,
    'ai-cybersecurity': AICybersecurityProgram,
    'ai-blockchain': AIBlockchainProgram,
    'agriculture-robotics': AgricultureRoboticsProgram,
    'agri-entrepreneurship': AgriEntrepreneurshipProgram,
    'precision-agriculture': PrecisionAgricultureProgram,
    'hydroponics-farming': HydroponicsFarmingProgram,
    'fermentation-technology': FermentationTechnologyProgram,
    'vaccine-technology': VaccineTechnologyProgram,
    'medical-coding': MedicalCodingProgram,
    'ip-law': IPLawProgram,
    'regulatory-affairs': RegulatoryAffairsProgram
  };

  // Get the component for the requested program
  const ProgramComponent = programComponents[programSlug || ''];

  if (!ProgramComponent) {
    return (
      <div className="program-details-page">
        <div className="container">
          <div className="error-state">
            <h2>Program Not Found</h2>
            <p>The requested program "{programSlug}" could not be found. Please go back to the programs page and try again.</p>
            <p>Available programs: {Object.keys(programComponents).slice(0, 10).join(', ')}...</p>
          </div>
        </div>
      </div>
    );
  }

  return <ProgramComponent />;
};

export default ProgramRouter;
